utils/oscap-podman: force removal of temporary container
In some cases there are errors printed by `oscap-podman` script, it
reports about failure to remove certain paths related to a container
that is spawned by it. This seems as a race condition in `oscap-podman`
where the `podman-rm` is called right after the `podman-umount` - this
might cause that system is not fully finished with unmounting and we
request it to remove the container without waiting for the unmount of
its filesystem. This commit removes `podman-umount` command and adds
`-f` option to `podman-rm` which should take care about both, unmounting
and removing of the temporary container.

diff --git a/utils/oscap-podman b/utils/oscap-podman
--- a/utils/oscap-podman
+++ b/utils/oscap-podman
@@ -110,8 +110,11 @@ shift 1
 $OSCAP_BINARY "$@"
 EXIT_CODE=$?
 
-podman umount $ID > /dev/null || die "Failed to unmount."
 if [ $CLEANUP -eq 1 ]; then
-    podman rm $ID > /dev/null || die "Failed to clean up."
+    # podman-rm should handle also unmounting of the container filesystem.
+    podman rm -f $ID > /dev/null || die "Failed to clean up."
+else
+    # If a running container is target of the scan just unmount its filesystem.
+    podman umount $ID > /dev/null || die "Failed to unmount."
 fi
 exit $EXIT_CODE
