Use hash instead of which in oscap-vm
Same as parent commit. This also gets rid of ShellCheck warnings in
oscap-vm. Resolves:

/usr/bin/oscap-vm:97:27: error: Can't use > in [ ]. Escape it or use [[..]]. [SC2073]
/usr/bin/oscap-vm:97:6: warning: Quote this to prevent word splitting. [SC2046]
/usr/bin/oscap-vm:99:27: error: Can't use > in [ ]. Escape it or use [[..]]. [SC2073]
/usr/bin/oscap-vm:99:8: warning: Quote this to prevent word splitting. [SC2046]

diff --git a/utils/oscap-vm b/utils/oscap-vm
--- a/utils/oscap-vm
+++ b/utils/oscap-vm
@@ -92,18 +92,18 @@ else
     die
 fi
 
-which guestmount > /dev/null || die "Cannot find guestmount, please install libguestfs utilities."
+hash guestmount 2> /dev/null || die "Cannot find guestmount, please install libguestfs utilities."
 
-if [ `which guestunmount` > /dev/null ]; then
+if hash guestunmount 2> /dev/null; then
     UNMOUNT_COMMAND="guestunmount"
-elif [ `which fusermount` > /dev/null ]; then
+elif hash fusermount 2> /dev/null; then
     echo "guestunmount command not present on the system, using simpler fusermount instead"
     UNMOUNT_COMMAND="fusermount -u"
 else
     die "Cannot find guestunmount or fusermount, please install libguestfs utilities, or fuse."
 fi
 
-which mktemp > /dev/null || die "Cannot find mktemp, please install coreutils."
+hash mktemp 2> /dev/null || die "Cannot find mktemp, please install coreutils."
 
 MOUNTPOINT=$(mktemp -d)
 
